<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>clojure-cli.repl-client</artifactId>
  <name>clojure-cli.repl-client</name>
  <description>Terminal client for clojure-cli.repl.</description>

  <parent>
    <groupId>io.github.clojure</groupId>
    <artifactId>clojure-cli.repl</artifactId>
    <version>0.1.1</version>
  </parent>

  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>${clojure.version}</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>tools.reader</artifactId>
      <version>1.6.0</version>
    </dependency>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>tools.deps.config</artifactId>
      <version>0.1.5</version>
    </dependency>
    <dependency>
      <groupId>org.jline</groupId>
      <artifactId>jline</artifactId>
      <version>4.3.1</version>
    </dependency>
    <dependency>
      <groupId>rewrite-clj</groupId>
      <artifactId>rewrite-clj</artifactId>
      <version>1.2.54</version>
    </dependency>
    <dependency>
      <groupId>nrepl</groupId>
      <artifactId>nrepl</artifactId>
      <version>1.7.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-clojure-source-dirs</id>
            <configuration>
              <sources combine.children="append">
                <source>src-jvm</source>
              </sources>
              <resources combine.children="append">
                <resource>
                  <directory>src-jvm</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.theoryinpractise</groupId>
        <artifactId>clojure-maven-plugin</artifactId>
        <configuration>
          <sourceDirectories combine.children="append">
            <sourceDirectory>src-jvm</sourceDirectory>
          </sourceDirectories>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
